Repository 42MonthsAfter/42MonthsAfter-Prod, pull requests merged in 2021-11, with the labels that each got.

#236 PVEZ Update
  mpmissions/dayzoffline.chiemsee/storage_1/players.db
  myprofile/Airdrop/AirdropSettings_bakup_2021-11-19 @ 22-03-09.json
  myprofile/PVEZ/Admins.txt
  myprofile/PVEZ/Config.json
  myprofile/PVEZ/Zones.json
  start.bat - Shortcut.lnk
Labels: Chiemsee, v11 Update

#237 Update ALL spawn locations
  mpmissions/dayzoffline.chiemsee/db/events.xml
  mpmissions/dayzoffline.chiemsee/env/bear_territories.xml
  mpmissions/dayzoffline.chiemsee/env/hen_territories.xml
  mpmissions/dayzoffline.chiemsee/env/pig_territories.xml
  mpmissions/dayzoffline.chiemsee/env/polar_bear_territories.xml
  mpmissions/dayzoffline.chiemsee/env/red_deer_territories.xml
  mpmissions/dayzoffline.chiemsee/env/roe_deer_territories.xml
  mpmissions/dayzoffline.chiemsee/env/scorpion_territories.xml
  mpmissions/dayzoffline.chiemsee/env/sheep_goat_territories.xml
  mpmissions/dayzoffline.chiemsee/env/wild_boar_territories.xml
  mpmissions/dayzoffline.chiemsee/env/wolf_territories.xml
  mpmissions/dayzoffline.chiemsee/env/zombie_territories.xml
  mpmissions/dayzoffline.chiemsee/storage_1/players.db
  myprofile/Airdrop/AirdropSettings_bakup_2021-11-19 @ 23-14-28.json
Labels: Chiemsee, v11 Update

#239 Updated Faction Traders
  myprofile/TraderPlus/TraderPlusConfig/TraderPlusIDsConfig.json
  myprofile/TraderPlus/TraderPlusConfig/TraderPlusPriceConfig.json
Labels: Chiemsee, v11 Update

#244 Update types.xml
  mpmissions/dayzoffline.chiemsee/db/types.xml
Labels: Chiemsee, v11 Update

#246 Trader Clean Up
  myprofile/TraderPlus/TraderPlusConfig/TraderPlusIDsConfig.json
  myprofile/TraderPlus/TraderPlusConfig/TraderPlusPriceConfig.json
Labels: Chiemsee, v11 Update

#254 Fix spawning blueprint walls
  mpmissions/dayzoffline.chiemsee/db/types.xml
Labels: bug, Chiemsee, v11 Update

#259 Tools Trader
  myprofile/TraderPlus/TraderPlusConfig/TraderPlusIDsConfig.json
  myprofile/TraderPlus/TraderPlusConfig/TraderPlusPriceConfig.json
Labels: enhancement, Chiemsee, v11 Update

#258 Food Trader Pricing
  myprofile/TraderPlus/TraderPlusConfig/TraderPlusPriceConfig.json
Labels: bug, Chiemsee, v11 Update

#266 Hunting Trader/Quickstop
  mpmissions/dayzoffline.chiemsee/EditorFiles/Hunting Trader.dze
  mpmissions/dayzoffline.chiemsee/EditorFiles/QuickStop2.dze
Labels: Chiemsee, v11 Update

#269 Trader config
  myprofile/TraderPlus/TraderPlusConfig/TraderPlusPriceConfig.json
Labels: Chiemsee, v11 Update

#283 Sell ammo to faction trader #282
  myprofile/TraderPlus/TraderPlusConfig/TraderPlusPriceConfig.json
Labels: bug, Chiemsee

#290 Hunter Trader Can't Buy or Sell Anything #286
  myprofile/TraderPlus/TraderPlusConfig/TraderPlusPriceConfig.json
Labels: bug, Chiemsee

#289 Grow Times #288
  myprofile/CannabisPlus/CannabisPlus.json
  myprofile/TraderPlus/TraderPlusConfig/TraderPlusIDsConfig.json
Labels: bug, Chiemsee

#291 Fixed Kits
  myprofile/TraderPlus/TraderPlusConfig/TraderPlusPriceConfig.json
Labels: bug, Chiemsee
